# Generated by Django 2.1.5 on 2019-02-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarow',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
