# Generated by Django 2.1.5 on 2019-02-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_app', '0002_auto_20190219_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarow',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
