# Generated by Django 2.1.5 on 2019-02-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_app', '0003_datarow_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='datarow',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='datarow',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_data_app.Country'),
        ),
    ]
