# Generated by Django 2.1.5 on 2019-02-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data_app', '0004_auto_20190220_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_html',
            field=models.FileField(default=' ', upload_to='charts/'),
            preserve_default=False,
        ),
    ]
